name: Publish Package to npmjs
on:
  push:
    branches:
      - master
jobs:
  run-tests:
    uses: ./.github/workflows/test.yml@master

  build:
    needs: [ run-tests ]
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: publish to npm
        run: |
          sudo apt-get install -y oathtool
          yarn
          yarn build
          OTP=$(oathtool -b --totp ${{ secrets.OTP_CODE }})
          npm publish --otp $OTP
