name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GIT_USER: devbro1
      GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: |
          git config --global user.email "docs@devbro.com"
          git config --global user.name "Docusaurus Bot"

          yarn install --frozen-lockfile
      # - name: Build Docusaurus site
      #   run: yarn workspace docs build
      - name: Build Docusaurus site
        # we are using gh-pages branch for docs website
        run: yarn workspace docs deploy
